mod test_config_dir_in_joins_cyolo;
mod test_config_path_in_joins_config_json;
mod test_save_in_then_load_in_round_trip;
mod test_load_in_missing_file_returns_default;
mod test_load_in_minimal_profiles_only_json;
mod test_load_in_corrupt_json_returns_parse_error;
mod test_save_in_permissions_dir_0700_file_0600;
mod test_ensure_dir_in_is_idempotent;
